<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aeb590b8-5da5-4bbe-aa12-a53851615904</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\Extra_Approved\New\**" />
    <Compile Remove="wwwroot\Extra_Approved\TESTING\**" />
    <Content Remove="wwwroot\Extra_Approved\New\**" />
    <Content Remove="wwwroot\Extra_Approved\TESTING\**" />
    <EmbeddedResource Remove="wwwroot\Extra_Approved\New\**" />
    <EmbeddedResource Remove="wwwroot\Extra_Approved\TESTING\**" />
    <None Remove="wwwroot\Extra_Approved\New\**" />
    <None Remove="wwwroot\Extra_Approved\TESTING\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.3" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="PuppeteerExtraSharp" Version="3.1.1" />
    <PackageReference Include="PuppeteerSharp" Version="21.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Config\" />
    <Folder Include="Databases\" />
    <Folder Include="Services\PhotoDownloaders\" />
    <Folder Include="wwwroot\Approved\" />
    <Folder Include="wwwroot\Extra_Approved\" />
    <Folder Include="wwwroot\Lookups\" />
    <Folder Include="wwwroot\ExternalIntegrationCache\" />
    <Folder Include="wwwroot\Convert\" />
    <Folder Include="wwwroot\PreviewImages\" />
    <Folder Include="wwwroot\VideoThumbnailsCache\" />
  </ItemGroup>

</Project>
